#!/bin/bash

API_URL="https://pokeapi.co/api/v2/pokemon/"

for name in Bulbasaur Ivysaur Venusaur Charmander Charmeleon; do
    lower_name=$(echo "$name" | tr '[:upper:]' '[:lower:]')
    response=$(curl -s -w "%{http_code}" "${API_URL}${lower_name}")

    http_code=${response: -3}
    response_body=${response:0:-3}

    if [ "$http_code" -eq 200 ]; then
        echo "$response_body" > "${lower_name}.json"
        echo "Saved data to ${lower_name}.json"
    else
        echo "Failed to fetch $name (HTTP $http_code)"
    fi
    echo ${lower_name}
done
