#!/bin/bash

name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
formatted_height=$(awk "BEGIN { printf \"%.1f\", $(jq -r '.height' data.json) / 10 }")
formatted_weight=$(awk "BEGIN { printf \"%.1f\", $(jq -r '.weight' data.json) / 10 }")
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
